sidecar:
  datasources:
    enabled: true
    label: grafana_datasource

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    node-exporter:
      gnetId: 10000
      revision: 1
      datasource: Prometheus
