apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-svc-ingress
spec:
  hosts:
    - "thesurfadvisor.com"
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
            prefix: /dictionary
      route:
        - destination:
            host: surf-dictionary
            port:
              number: 5001
    - match:
        - uri:
            prefix: /geolocation
      route:
        - destination:
            host: geolocation-service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /spots
      route:
        - destination:
            host: spot-service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /map-supplier
      route:
        - destination:
            host: map-supplier
            port:
              number: 8080
